# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2711445ad1ca2cbf0a38cd75d329ace1e3d22eb24934634d375a885882f04b2a375c2deb04a4ecbed845d48d27a0f0ab8af48a6cb4688e20fe5a8e368ced3d89

test:
  secret_key_base: dd7b6d26438074b63b77b5673eef9524a94fa392990b644336fa281b063e92176160064f7116310af3a17c8f73d8141392506b98b89b44a5cf26e08eb8d46006

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
